"""Shared constants for the ZPE XR Wave-1 harness."""

FPS = 90
HANDS = 2
JOINTS_PER_HAND = 26
TOTAL_JOINTS = HANDS * JOINTS_PER_HAND
RAW_FLOATS_PER_JOINT = 3  # position xyz only (codec does not encode rotations)
RAW_BYTES_PER_FRAME = TOTAL_JOINTS * RAW_FLOATS_PER_JOINT * 4

MAGIC = b"ZXR"
FORMAT_VERSION = 1

DEFAULT_KEYFRAME_INTERVAL = 45
DEFAULT_DEADBAND_MM = 1
NO_BACKUP_SEQ = 0xFFFF

MM_PER_METER = 1000.0
